# Generated by Django 2.1rc1 on 2018-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageText', models.CharField(max_length=200)),
                ('TelephonNumber', models.CharField(max_length=200)),
                ('PubDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
