# Generated by Django 2.1rc1 on 2018-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zayavka_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('zayavka_text', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'zayavka',
            },
        ),
    ]
